name: CI

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "pyproject.toml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "pyproject.toml"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -e .[dev]
      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=bfm --cov-report=term-missing --color=yes

  lint:
    name: lint (advisory)
    runs-on: ubuntu-latest
    needs: test
    if: always()                 # still run even if tests fail
    continue-on-error: true      # never fail the workflow due to lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - run: python -m pip install -U pip ruff
      - name: Ruff lint
        run: ruff check . --output-format=github
      - name: Ruff format (check only)
        run: ruff format --check .